const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Endboss(),
    ],
    [
        new Clouds('img/5_background/layers/4_clouds/1.png', 350),
        new Clouds('img/5_background/layers/4_clouds/2.png', 750),
        new Clouds('img/5_background/layers/4_clouds/1.png', 1150),
        new Clouds('img/5_background/layers/4_clouds/2.png', 1550),
        new Clouds('img/5_background/layers/4_clouds/1.png', 1950),
        new Clouds('img/5_background/layers/4_clouds/2.png', 2350),
        new Clouds('img/5_background/layers/4_clouds/1.png', 2750),
    ],
    [
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
    ],
    [
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
    ],
    [

        new BackgroundObjects('img/5_background/layers/air.png', -719),
        new BackgroundObjects('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObjects('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObjects('img/5_background/layers/1_first_layer/2.png', -719),

        new BackgroundObjects('img/5_background/layers/air.png', 0),
        new BackgroundObjects('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObjects('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObjects('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObjects('img/5_background/layers/air.png', 719),
        new BackgroundObjects('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObjects('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObjects('img/5_background/layers/1_first_layer/2.png', 719),

        new BackgroundObjects('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObjects('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObjects('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObjects('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObjects('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObjects('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObjects('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObjects('img/5_background/layers/1_first_layer/2.png', 719 * 3),
    ]
)